### ISSUE TITLE
TODO list for the example repo

### ISSUE THREAD

**Issue by marians** [giantswarm/example-opensource-repo#1]
- [x] add CONTRIBUTING.md
- [x] add MAINTAINERS file
- [x] add DCO (see CoreOS)
- [x] Set up example README (see below)
- [x] Set up CI with badge in README
- [x] set up `docs` folder
## README content
- What is it for? (short)
- What does it do exactly
- Future directions/vision
- How to build
  - dependencies
- How to install
  - prerequisites
- How to use
- How to contribute
- Link to godoc
- Link to public docker image
- CI info

**Comment by puja108** [comment]
first CONTRIBUTING.md in https://github.com/giantswarm/example-opensource-repo/pull/2

started structuring README and adding what we have above under content in https://github.com/giantswarm/example-opensource-repo/pull/3
